### ISSUE TITLE
Build problem (sed, windows)

### ISSUE THREAD

**Issue by Syphurith** [dukesrg/rop3ds#8]
@dukesrg I heard yours is a busybox one. Mine is GNU sed 4.2.1 provided by MSYS2.
While `make clean && make`.. it was like `sed -e "/17498'/{rLoadCode.utf8" -e "N}" -i index.html`.

```
generating SPIDER_4X ROP
/bin/sed: -e expression #1, char 50: unterminated `s' command
Makefile:31: recipe for target 'index.html' failed
make: *** [index.html] Error 1
```

If execute manually yes i could get sed working (with a f*cking backslash). If auto with `\` still fail.

```
sed -e "\/17498'/{rLoadCode.utf8" -e "N}" -i index.html
/bin/sed: -e expression #1, char 50: unterminated `s' command
Makefile:32: recipe for target 'index.html' failed
make: *** [index.html] Error 1
```

Some other lines would fail. It seems not be compatible to be executed manually.
`make -s LoadCode.dat ASFLAGS=-DSPIDER_4X -DSPIDER_ARM_CODE_OFFSET=0`
_Getting latest GNU sed source from gnu ftp.._ Oh my, there is 4.2.2-2 offered from MSYS2.

**Comment by Syphurith** [comment]
Orz the sed 4.2.1 from PortableGit.. 4.2.2-2 from MSYS2.. I hate different Mingw enviorments now..

**Comment by Syphurith** [comment]
@dukesrg Problem solved once i removed my portablegit path from System PATH and use MSYS2.

**Comment by dukesrg** [comment]
That's shy I recommend to use toolchain with devkitPro MSYS that was originally used :)

**Comment by Syphurith** [comment]
```
In file included from rop.S:4:0:
rop.h:425:3: error: #error ROP version not defined
  #error ROP version not defined
   ^
Makefile:12: recipe for target 'rop.elf' failed
make: *** [rop.elf] Error 1
```

Maybe you could remove `rop.dat LoadCode.dat LoadCodeMset.dat` from `make all`.

**Comment by Syphurith** [comment]
@dukesrg Wait. ~~The version devkitPro MSYS offered is a 4.2.1, which doesn't suite your makefile.~~

**Comment by dukesrg** [comment]
@Syphurith I'm building with that sed!
yes rop 3ds all rule is not quite right, just becase there is no need to make it all :)

**Comment by Syphurith** [comment]
@dukesrg on windows that sed version failed for me. so i would use newer one.

**Comment by dukesrg** [comment]
@Syphurith
If you setup toolchain like described in readme.md and remove all conflicting values from %path% it will work fine.

**Comment by Syphurith** [comment]
@dukesrg all right then since target `index.html` now build for me. _trouble maker, windows_

**Comment by dukesrg** [comment]
@Syphurith yes but you cant force all devs switch to linux - we'd rather have as many as possible since there are actually A LOT of things to fix and implement

**Comment by Syphurith** [comment]
@dukesrg Oh well. With devkitPro MSYS. I would have to run it in `cmd`, but turns out to be fine.
